image: docker:latest

services:
  - docker:dind

stages:
  - buildpublish


buildpublish:
  stage: publish
  script:
    - echo "Building image"
    - docker build --tag personal-website:latest .
    - echo "Publishing built image"
    - docker tag personal-website:latest mikepratt/personal-website:latest
    - docker push mikepratt/personal-website:latest
    - docker rmi personal-website:latest