image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_LOGIN_USER: ""
  DOCKER_LOGIN_PASSWORD: ""

stages:
  - build-and-publish


build-and-publish:
  stage: build-and-publish
  script:
    - echo "Building image"
    - docker build --tag personal-website:latest .
    - echo "Publishing built image"
    - docker tag personal-website:latest mikepratt/personal-website:latest
    - docker login -u ${DOCKER_LOGIN_USER} -p ${DOCKER_LOGIN_PASSWORD}
    - docker push mikepratt/personal-website:latest
    - docker rmi personal-website:latest