image: docker:latest

services:
  - docker:dind

stages:
  - build
  - publish

build:
  stage: build
  script:
    - echo "Building image"
    - docker build --tag personal-website:latest .

publish:
  stage: publish
  script:
    - echo "Publishing built image"
    - docker tag personal-website:latest mikepratt/personal-website:latest
    - docker push mikepratt/personal-website:latest
    - docker rmi personal-website:latest