image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_LOGIN_USER: ""
  DOCKER_LOGIN_PASSWORD: ""

stages:
  - build
  - publish

before_script:
  - docker login -u ${DOCKER_LOGIN_USER} -p ${DOCKER_LOGIN_PASSWORD}

build:
  stage: build
  script:
    - echo "Building image"
    - docker build --tag personal-website:latest .
    - docker save -o personal-website.tar personal-website:latest
  artifacts:
    paths:
      - personal-website.tar

publish:
  stage: publish
  dependencies:
    - build
  script:
    - echo "Publishing built image"
    - docker load -i personal-website.tar
    - docker tag personal-website:latest registry.gitlab.com/msjp/personal-website:latest
    - docker push registry.gitlab.com/msjp/personal-website:latest
    - docker rmi personal-website:latest