image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_LOGIN_USER: ""
  DOCKER_LOGIN_PASSWORD: ""

stages:
  - build
  - publish

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  except:
    - master
  script:
    - echo "Building image"
    - docker build --tag personal-website:$CI_COMMIT_REF_SLUG .
    - docker save -o personal-website.tar personal-website:$CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - personal-website.tar

publish:
  stage: publish
  except:
    - master
  dependencies:
    - build
  script:
    - echo "Publishing built image"
    - docker load -i personal-website.tar
    - docker tag personal-website:$CI_COMMIT_REF_SLUG registry.gitlab.com/msjp/personal-website:$CI_COMMIT_REF_SLUG
    - docker push registry.gitlab.com/msjp/personal-website:$CI_COMMIT_REF_SLUG
    - docker rmi personal-website:$CI_COMMIT_REF_SLUG

build-master:
  stage: build
  only:
    - master
    - tags
  script:
    - echo "Building (master) image"
    - docker build --tag personal-website:master-$CI_COMMIT_TAG .
    - docker save -o personal-website.tar personal-website:master-$CI_COMMIT_TAG
  artifacts:
    paths:
      - personal-website.tar

publish-master:
  stage: publish
  only:
    - master
    - tags # doesn't stop it running
  dependencies:
    - build-master
  script:
    - echo "Publishing built (master) image"
    - docker load -i personal-website.tar
    - docker tag personal-website:master-$CI_COMMIT_TAG registry.gitlab.com/msjp/personal-website:master-$CI_COMMIT_TAG
    - docker push registry.gitlab.com/msjp/personal-website:master-$CI_COMMIT_TAG
    - docker rmi personal-website:master-$CI_COMMIT_TAG