apiVersion: v1
kind: Secret
metadata:
  name: personal-website-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjp7CiAgICAgICAgImh0dHBzOi8vcmVnaXN0cnkuZ2l0bGFiLmNvbSI6ewogICAgICAgICAgICAidXNlcm5hbWUiOiJtc2pwIiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiaWQ0WnhZaG1TVnBaeFJzc0RWWlAiLAogICAgICAgICAgICAiZW1haWwiOiJtaWtlcDI0MTlAZ21haWwuY29tIiwKICAgICAgICAgICAgImF1dGgiOiJiWE5xY0RwcFpEUmFlRmxvYlZOV2NGcDRVbk56UkZaYVVBPT0iCiAgICAgICAgfQogICAgfQp9