import Navbar from "./Navbar";
import Head from "next/head";
import Footer from "./Footer";

export default function Layout({ children }) {
    return (
        <div className="flex w-full h-screen justify-between dark:bg-slate-800">
            <Head>
                <title>Mike Pratt - Software Engineer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex w-full flex-col">
                <header>
                    <Navbar />
                </header>
                <main className="w-full flex-grow">
                    {children}
                </main>
                <footer>
                    <Footer />
                </footer>
            </div>
        </div>
    );
}
