import Navbar from "./Navbar";
import Head from "next/head";

export default function Layout({ children }) {
    return (
        <div className="flex w-full justify-center h-screen dark:bg-slate-800">
            <Head>
                <title>Mike Pratt - Software Engineer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex w-full flex-col">
                <header>
                    <Navbar />
                </header>
                <main className="h-full w-full">
                    {children}
                </main>
            </div>
        </div>
    );
}
